# Generated by Django 5.1.4 on 2024-12-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('T', 'Tree Nurseries'), ('V', 'Vegetable Nurseries'), ('O', 'Ornmental Nurseries')], max_length=1)),
                ('file', models.ImageField(upload_to='nurseries/')),
            ],
        ),
    ]
