# Generated by Django 5.1.4 on 2024-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_nurseries_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseries',
            name='category',
            field=models.CharField(choices=[('Tree', 'Tree Nurseries'), ('Vegetable', 'Vegetable Nurseries'), ('Ornmental', 'Ornmental Nurseries')], max_length=20),
        ),
    ]
