# Generated by Django 5.1.4 on 2024-12-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_nurseries_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseries',
            name='category',
            field=models.CharField(choices=[('Tree Nurseries', 'Tree Nurseries'), ('Vegetable Nurseries', 'Vegetable Nurseries'), ('Ornmental Nurseries', 'Ornmental Nurseries')], max_length=50),
        ),
    ]
