# Generated by Django 5.1.4 on 2024-12-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_nurseries_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(verbose_name='Planting day')),
                ('image_url', models.TextField(max_length=1000)),
                ('nurseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nurseries')),
            ],
        ),
    ]
