# Generated by Django 5.1.4 on 2024-12-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fertilization Time')),
                ('ferStatus', models.CharField(choices=[('Fertilized', 'Fertilized'), ('Needs Fertilization', 'Needs Fertilization'), ('Over-Fertilized', 'Over-Fertilized'), ('Not Fertilized', 'Not Fertilized'), ('Inappropriate Fertilizer', 'Inappropriate Fertilizer')], max_length=50)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plants')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Irrigation Time')),
                ('irrStatus', models.CharField(choices=[('Irrigated', 'Irrigated'), ('Needs Irrigation', 'Needs Irrigation'), ('Overwatered', 'Overwatered'), ('Not Watered', 'Not Watered'), ('Irrigation Delayed', 'Irrigation Delayed')], max_length=50)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plants')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PestControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Pest Control')),
                ('pestStatus', models.CharField(choices=[('No Pests', 'No Pests'), ('Pest Control Applied', 'Pest Control Applied'), ('Few Pests', 'Few Pests'), ('Severe Pest Infestation', 'Severe Pest Infestation'), ('Recurring Pest Issue', 'Recurring Pest Issue'), ('Unknown Pest Type', 'Unknown Pest Type')], max_length=50)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plants')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
