# Generated by Django 5.1.4 on 2024-12-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_fertilization_irrigation_pestcontrol'),
        ('main_app', '0007_remove_product_image_product_image_url_and_more'),
    ]

    operations = [
    ]
