# Generated by Django 5.1.4 on 2024-12-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20241209_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Status record day')),
                ('note', models.TextField(max_length=1000)),
                ('color', models.CharField(max_length=20)),
                ('plant_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Caution', 'Caution'), ('Requires Immediate Care', 'Requires Immediate Care')], default='Healthy', max_length=50)),
            ],
        ),
    ]
