# Generated by Django 5.1.4 on 2024-12-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='plants',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main_app.plants'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='green', max_length=20),
        ),
    ]
