# Generated by Django 5.1.4 on 2024-12-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
